### ISSUE TITLE
Db heal reports not existing checkpoint

### ISSUE THREAD

**Issue by cabrador** [Fantom-foundation/Carmen#1010]
Running `db-heal-test.py` with checkpoint created every 5 blocks results in Carmen reporting checkpoint at block that is not divisible by 5 i.e.
`block 265 is beyond the last checkpoint height of 252`

To reproduce `python3 db-heal-test.py --aida /path/to/aida@develop --aida-db /path/to/aida-db --window 1 --cp-granularity 5`

**Comment by HerbertJordan** [comment]
The reason for the checkpoint block not being divisible by 5 is that checkpoints are created for the first non-empty block after the requested checkpoint height.

So, if a checkpoint should be created every 5 blocks, and blocks 250 and 251 are empty, a checkpoint for block 252 is created.
