### ISSUE TITLE
Use a Pool to reuse read buffers in File Stock

### ISSUE THREAD

**Issue by HerbertJordan** [Fantom-foundation/Carmen#577]
This allocation could be improved by using a `sync.Pool`:
https://github.com/Fantom-foundation/Carmen/blob/278d3057918e1919fa726f4532d470449363bf48/go/backend/stock/file/file.go#L195C14-L195C34

**Comment by kjezek** [comment]
fixed in https://github.com/Fantom-foundation/Carmen/pull/814
