### ISSUE TITLE
S5: Large Bulk Loads into an S5 DB faile due to limited node cache

### ISSUE THREAD

**Issue by HerbertJordan** [Fantom-foundation/Carmen#789]
Right now, large bulk loads need to be split into smaller bulk loads distributed over multiple blocks because Carmen S5 has a limit number of modifications per block (see #686). This is not documented in the Carmen Facade.

Ideally this limitation is removed by enabling arbitrary large bulk load operations on a single block on S5 structures.

**Comment by petr-hanzl** [comment]
This code will become deprecated soon, as `genesis` files are being introduced for priming and its only usage is in Aida.
