### ISSUE TITLE
GetArchiveBlockHeight() sometimes returns incorrect data

### ISSUE THREAD

**Issue by petr-hanzl** [Fantom-foundation/Carmen#845]
`GetArchiveBlockHeight()` is flaky and sometimes returns incorrect data when running 
`./build/aida-vm-sdb substate --db-impl carmen --db-variant go-file --carmen-schema 5 --db-tmp /var/data/tmp --aida-db /var/data/aida-db --track-progress --workers=40  --archive --archive-variant s5 --archive-query-rate 2000 0 1000`
it returns that Archive is already on block `X` but when `GetArchiveState(X)` is called, it returns error `block does not exist`.

This only happens sometimes at the beginning of the run so you might need to run the command multiple times to trigger this bug.

**Comment by kjezek** [comment]
fixed by #848
