### ISSUE TITLE
Provide access to memory footprint information in public API

### ISSUE THREAD

**Issue by HerbertJordan** [Fantom-foundation/Carmen#864]
A summary of memory usage information should be provided through the public API, as it is provided right now through the internal StateDB interface ([here](https://github.com/Fantom-foundation/Carmen/blob/dddf65b4e1f3b09c884d10eb97d23399cf07ea74/go/state/state_db.go#L137)).

For this, a cleaner version of the [common.MemoryFootprint](https://github.com/Fantom-foundation/Carmen/blob/dddf65b4e1f3b09c884d10eb97d23399cf07ea74/go/common/mem_footprint.go#L20) should be defined in the Carmen package, and then made available through the facade.

**Comment by cabrador** [comment]
Done in #946
