### ISSUE TITLE
Witness Proof verification utilities

### ISSUE THREAD

**Issue by HerbertJordan** [Fantom-foundation/Carmen#865]
Carmen should provide utilities for verifying witness proofs. In particular, two types of tools are required:
 - a general verification tool, checking whether a given proof is valid
 - a set of utilities to check whether a given proof supports the following statements:
    - account X has balance Y
    - account X has nonce Y
    - account X has a code with hash Y
    - in account X the storage location Y has value Z

More advanced utilities may cover the following:
 - the proof shows that account X does not exist / is empty
 - the proof shows that in account X all keys in the range [Y,Z] have the value 0

**Comment by kjezek** [comment]
addressed in #903
