### ISSUE TITLE
The Test TestNodeFlusher_TriggersFlushesPeriodically is flaky

### ISSUE THREAD

**Issue by HerbertJordan** [Fantom-foundation/Carmen#981]
The test [TestNodeFlusher_TriggersFlushesPeriodically](https://github.com/Fantom-foundation/Carmen/blob/81e342a258101a641c66783deb657c3cf62965bc/go/database/mpt/node_flusher_test.go#L46) is flaky, sometimes failing the nightly race-detection tests (example [here](https://scala.fantom.network/job/Carmen/job/Race-Detection/123/)).

**Comment by kjezek** [comment]
fixed by #1035
