### ISSUE TITLE
Test TestArchiveTrie_RestoreBlockHeight failed in Jenkins environment

### ISSUE THREAD

**Issue by HerbertJordan** [Fantom-foundation/Carmen#994]
The the Race-Detectors' run [#126](https://scala.fantom.network/job/Carmen/job/Race-Detection/126/console) the test `TestArchiveTrie_RestoreBlockHeight` failed with the following message:
```
01:33:21  --- FAIL: TestArchiveTrie_RestoreBlockHeight (21.55s)
01:33:21      --- FAIL: TestArchiveTrie_RestoreBlockHeight/no_close_with_extra_blocks (5.04s)
01:33:21          archive_trie_test.go:2373: failed to verify archive: contains invalid reference to node A-123
01:33:21              contains invalid reference to node A-122
```

The reason is unclear and should be investigated. This may indicate an issue with the checkpoint / recovery procedure.

**Comment by kjezek** [comment]
I could reproduce it locally while running

`go test -count 1000 -timeout 5h -run TestArchiveTrie_RestoreBlockHeight/no_close_with_extra_blocks`

**Comment by kjezek** [comment]
I could debug that the upper bound of the stock is `122`, and there is a node ref. `123`, i.e. the reference `123` is not valid.

**Comment by kjezek** [comment]
fixed by disabling node flusher in the test (the node flusher was causing extra nodes being stored to the stock)

https://github.com/Fantom-foundation/Carmen/pull/1038
